name: Build and Test

on:
 push:
    branches: [ "main" ]

jobs:
  build:
  
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setupup Java JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build
        working-directory: ./java
        run: javac -cp "./dependencies/gson-2.9.1.jar" ./src/lab2/Person.java ./src/lab2/Main.java

      - name: Test Equals
        working-directory: ./java
        run: |
         javac -cp "./testing/junit-platform-console-standalone-1.9.0.jar:./dependencies/gson-2.9.1.jar:./dependencies/equalsverifier-3.10.1.jar" ./src/lab2/Person.java ./src/lab2/PersonEqualsTest.java
         java -jar ./testing/junit-platform-console-standalone-1.9.0.jar -cp "./dependencies/byte-buddy-1.12.8.jar:./dependencies/objenesis-3.3.jar:./dependencies/equalsverifier-3.10.1.jar:./dependencies/gson-2.9.1.jar:./src" --select-class lab2.PersonEqualsTest
